### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Timtaran** [WaterfallMC/Waterfall#728]
Error:
```
Could not connect to a default or fallback server. Incorrectly configured address/port/firewall? ConnectTimeoutException : connection timed out: n1.luxxy.tech/178.128.174.71:5189
```
Config:
```
server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: false
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:5673
  max_players: 1
  motd: '&1Another Bungee server'
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: false
  query_port: 25573
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: true
stats: 90756aea-42fd-431d-9117-7faaef99b9e2
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    address: n1.luxxy.tech:5189
    motd: '&1Just another Waterfall - Forced Host'
    restricted: false
```
