### ISSUE TITLE
Make MOTD follow server priorities

### ISSUE THREAD

**Issue by Carson365** [WaterfallMC/Waterfall#782]
As it is implemented currently, the MOTD ignores the settings for server fallbacks and defaults.
Ideally, the following changes to the MOTD behavior should be made for continuity with server fallback behavior:
```
priorities:
  - First
  - Second
servers:
  First:
    motd: 'First Server!'
    address: localhost:25564
    restricted: false
  Second:
    motd: 'Second Server!'
    address: localhost:25566
    restricted: false
```
if 'First' is offline the player will be connected to 'Second', so the MOTD for 'Second' should be displayed.
if all servers are offline, the player should see the MOTD of the Waterfall server.

This is in-line with the fallback behavior of the servers themselves, so it should be expected that the MOTDs would behave this way as well.

Since this behavior may not be desirable for all server owners, I suggest either tying it to the `force_default_server` setting since it already affects what MOTD is shown, or adding an additional setting to accomodate the change.
